{% set generic_ver = "1.8" %}
{% set europe_ver = "1.6" %}
{% set north_america_ver = "1.4" %}
{% set oceania_ver = "1.2" %}
{% set world_ver = "1.0" %}

package:
  name: datumgrid

source:
  - url: http://download.osgeo.org/proj/proj-datumgrid-{{ generic_ver }}.tar.gz
    sha256: 3ff6618a0acc9f0b9b4f6a62e7ff0f7bf538fb4f74de47ad04da1317408fcc15
    folder: proj-datumgrid

  - url: http://download.osgeo.org/proj/proj-datumgrid-europe-{{ europe_ver }}.tar.gz
    sha256: af2f4f364d84eb9d5ca23403f8540ae8daee54ec900903bc92d48afb1ed285f8
    folder: proj-datumgrid-europe

  - url: http://download.osgeo.org/proj/proj-datumgrid-north-america-{{ north_america_ver }}.tar.gz
    sha256: 95a6cdcdc078caed412ea66d3fdd2f699286336d5ca6c98bffb2d7132585ce40
    folder: proj-datumgrid-north-america

  - url: http://download.osgeo.org/proj/proj-datumgrid-oceania-{{ oceania_ver }}.tar.gz
    sha256: 952c43886c9ed6a098c308de61161a00cbe83fbb0f6e9e43c0c25c323bb06a4c
    folder: proj-datumgrid-oceania

  - url: http://download.osgeo.org/proj/proj-datumgrid-world-{{ world_ver }}.tar.gz
    sha256: a488a5a69d1af6ec2ee83a2c64c52adac52e6dbfafe883f0341340009a9f40ba
    folder: proj-datumgrid-world

build:
  number: 5

requirements:
  run:
    - proj

test:
  commands:
    # TODO: we need real tests for each datumgrid.
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975

outputs:
  - name: proj-datumgrid
    version: {{ generic_ver }}
    script: install.sh  # [not win]
    script: install.bat  # [win]

  - name: proj-datumgrid-europe
    version: {{ europe_ver }}
    script: install.sh  # [not win]
    script: install.bat  # [win]

  - name: proj-datumgrid-north-america
    version: {{ north_america_ver }}
    script: install.sh  # [not win]
    script: install.bat  # [win]

  - name: proj-datumgrid-oceania
    version: {{ oceania_ver }}
    script: install.sh  # [not win]
    script: install.bat  # [win]

  - name: proj-datumgrid-world
    version: {{ world_ver }}
    script: install.sh  # [not win]
    script: install.bat  # [win]

about:
  home: https://github.com/OSGeo/proj-datumgrid
  license: Public domain | X/MIT | BSD-2/3/4-Clause | CC0 | CC-BY (v3.0 or later) | CC-BY-SA (v3.0 or later)
  # Each package has a README file with the license info, that is copied with the datum files.
  # license_file: README.<name>
  summary: 'Cartographic Projections and Coordinate Transformations Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
