travis:
  secure:
    BINSTAR_TOKEN: HnaMopNaxrU7WWFY1rHmJbywOQ4iiA3y0Egp/m5BCaj8AMIIYi7FXKD6G1Ek4s6Qva9bo3FX5QEI4XkycF1UTWkpj17Pr96mESFydd38tkCSIrmrFKgwQJqz9781EbEYwNWxfZVusXLOfKbUL8a+jT08qCmApzoISCjocCcdqBDnwrwDT7OQdm9UZHzpI7a9H4qwQ+bMq6DZB3dMKitxDLcJIik/hGp7zEQqZXEqgjcRKvLWbNC95k4osoxotT6c7KQ6ivEre5h/fK9rTo93L7hYwc5SKVIbfghjF8Yg1NCbhIBjp7xjMBYvOZ5SJ5h6f21VCg9vLCMac+rEv0t+H3ZRCdmW84oK/I9f2GiYBod+Ra20BJ6ugCBDxBqzZWSflYfq6u3ekOjyN27HZxaRRmP/TSTG5nWeUxGC+KR5bBlj3RjbHLnKFrjcCLmM3BP+LFPL/7cJjVE+4Y27jp3nIRYy8ircRaOcSdwlgqJS4zqFLkEnNiA/BvW0bRtA9dOjm35pdt+3m3RcspoTGZ1+2PlBKYq7/XlZRDJg6o22FumAaaGY3YyIlfYbQY9ZsayDgwSNujaqIt9aRBOn4IfZLTSapRj57zWuqCujHW5UtdOpZtrpD2TNwtrAqeAVsBXtRvp+pd507vn+I7CI6pdeKGt0FbwMhxgsUnWRDbjbp2w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
